// Weather constants
export const CURRENT_WEATHER_FETCHED = 'CURRENT_WEATHER_FETCHED';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const UPDATE_FAVORITES_WEATHER = 'UPDATE_FAVORITES_WEATHER';
export const SET_ERR = 'SET_ERR';

// Environment constants
export const TOGGLE_DEGREES = 'TOGGLE_DEGREES';
export const TOGGLE_THEME_SUPPORT = 'TOGGLE_THEME_SUPPORT';
